from SinglyLinkedList import SinglyLinkedList
myList = SinglyLinkedList()
myList.addFirst(5)
myList.addFirst(2)
myList.addFirst(9)
myList.addFirst(7)
myList.display()
myList.addLast(15)
myList.addLast(21)
myList.addLast(2)
myList.addLast(21)
myList.addLast(17)
myList.addLast(15)
myList.display()
# print(f"Number of nodes: {myList.countNodes()}")
# n=int(input("Input the position to get value: "))
# val=myList.getValueAtPos(n)
# if val!=-999:
#     print(f"The value at position {n} is: {val}")
# else:
#     print(f"{n} is out of range")
# pos=int(input("Input the position to add value: "))
# x=int(input("Input the value to add: "))
# myList.addNodeAtPos(x, pos)
# myList.display()
# myList.removeFirst()
# myList.display()
# myList.removeLast()
# myList.display()
# Remove node at pos
# pos=int(input("Input the position to remove: "))
# myList.removeNodeAtPos(pos)
# myList.display()
# print(f"Find max min: max = {myList.getMaxValue()}, min = {myList.getMinValue()}")
# print("Find the position of the-k maximum value.")
# k=int(input("Input the-k to get max value: "))
# pos=myList.getPosOfMaxTheK(k)
# if pos != -1:
#     print(f"The position of th-{k} maximum value: {pos}")
# else:
#     print(f"Find not found the-{k} maximum value")
# print("Find the position of the-k maximum value.")

# k=int(input("Input the-k to get min value: "))
# pos=myList.getPosOfMinTheK(k)
# if pos != -1:
#     print(f"The position of th-{k} minimum value: {pos}")
# else:
#     print(f"Find not found the-{k} maximum value")
# print("Sort ASC")
# myList.SortListAsc()
# myList.display()

print("Sort Desc")
myList.SortListDesc()
myList.display()