from DoubleLinkedList import DoubleLinkedList
myList=DoubleLinkedList()
myList.addFirst(6)
myList.addFirst(2)
myList.addFirst(9)
myList.addFirst(5)
myList.display()
print("\n")
myList.addLast(12)
myList.addLast(24)
myList.addLast(31)
myList.addLast(44)
myList.display()
print(f"\nNumber of nodes is: {myList.countNode()}")
print("Remove first")
myList.removeFirst()
myList.display()
print("\nRemove last")
myList.removeLast()
myList.display()
# print("\nAdd node at pos")
# x=int(input("Input x = "))
# pos=int(input("Input position to add pos = "))
# myList.addAtPost(x, pos)
# myList.display()
print("\nRemove at pos")
pos=int(input("Input position to remove: "))
myList.removeAtPos(pos)
myList.display()
print("\nSort")
myList.sortListAsc()
myList.display()
