from BSTree import BSTree
myT = BSTree()
myT.addTreeNode(12)
myT.addTreeNode(9)
myT.addTreeNode(15)
myT.addTreeNode(7)
myT.addTreeNode(11)
myT.addTreeNode(13)
myT.addTreeNode(18)
myT.addTreeNode(5)
myT.addTreeNode(10)
myT.addTreeNode(14)
myT.addTreeNode(6)
myT.addTreeNode(2)
myT.addTreeNode(3)
myT.addTreeNode(21)
myT.inOrder(myT.root)
print("\nPre order traversal")
myT.preOrder(myT.root)
print("\nPost order traversal")
myT.postOrder(myT.root)
print("\nBFS")
myT.breadth_first_traversal()
print(f"\nNumber of nodes have two children: {myT.countNodeHasTwoChildren()}")
print(f"Number of nodes have a left child: {myT.countNodesHasOnlyLeftChild(myT.root)}")
print(f"Number of nodes have a right child: {myT.countNodesHasOnlyRightChild(myT.root)}")
x=int(input("Input threshold x = "))
print(f"Number of nodes greater than {x} is {myT.countNodesWithValueGreaterThanX(myT.root,x)}")
