from BSTree import BSTree
myT = BSTree()
myT.addTreeNode(9)
myT.addTreeNode(6)
myT.addTreeNode(8)
myT.addTreeNode(12)
myT.addTreeNode(4)
myT.addTreeNode(2)
myT.addTreeNode(5)
myT.addTreeNode(3)
myT.inOrder(myT.root)
print("\nPre order traversal")
myT.preOrder(myT.root)
print("\nPost order traversal")
myT.postOrder(myT.root)